export const users = [
  {
    fullName: "Alice Muthoni",
    role: "admin",
    contributionsCount: 42,
    email: "alice.muthoni@example.com",
    username: "alice_m",
  },
  {
    fullName: "Brian Otieno",
    role: "user",
    contributionsCount: 15,
    email: "brian.otieno@example.com",
    username: "brian_o",
  },
  {
    fullName: "Cynthia Mwikali",
    role: "user",
    contributionsCount: 9,
    email: "cynthia.mwikali@example.com",
    username: "cynthia_m",
  },
  {
    fullName: "David Kamau",
    role: "admin",
    contributionsCount: 33,
    email: "david.kamau@example.com",
    username: "david_k",
  },
  {
    fullName: "Esther Wanjiru",
    role: "user",
    contributionsCount: 7,
    email: "esther.wanjiru@example.com",
    username: "esther_w",
  },
  {
    fullName: "Felix Mutiso",
    role: "user",
    contributionsCount: 12,
    email: "felix.mutiso@example.com",
    username: "felix_m",
  },
  {
    fullName: "Grace Achieng",
    role: "admin",
    contributionsCount: 28,
    email: "grace.achieng@example.com",
    username: "grace_a",
  },
  {
    fullName: "Hassan Juma",
    role: "user",
    contributionsCount: 19,
    email: "hassan.juma@example.com",
    username: "hassan_j",
  },
  {
    fullName: "Irene Naliaka",
    role: "user",
    contributionsCount: 6,
    email: "irene.naliaka@example.com",
    username: "irene_n",
  },
  {
    fullName: "James Kariuki",
    role: "user",
    contributionsCount: 23,
    email: "james.kariuki@example.com",
    username: "james_k",
  },
  {
    fullName: "Kevin Mwangi",
    role: "admin",
    contributionsCount: 35,
    email: "kevin.mwangi@example.com",
    username: "kevin_m",
  },
  {
    fullName: "Linda Chebet",
    role: "user",
    contributionsCount: 14,
    email: "linda.chebet@example.com",
    username: "linda_c",
  },
  {
    fullName: "Michael Oduor",
    role: "user",
    contributionsCount: 11,
    email: "michael.oduor@example.com",
    username: "michael_o",
  },
];
